### ISSUE TITLE
Client reports that connection failed due to timeout even though connection succeeded

### ISSUE THREAD

**Issue by atbe** [livekit/client-sdk-js#9]
Hi,

We're running the latest client sdk and livekit server and I'm seeing this when connecting to a call:

![image](https://user-images.githubusercontent.com/987031/113615653-1dec1e00-9622-11eb-9d94-3fe2707e3b50.png)

**Comment by zhuwei** [comment]
I have the same problem

**Comment by zhuwei** [comment]
![image](https://user-images.githubusercontent.com/1817493/127126839-808f307e-5c57-4539-a240-91fa2f8ed872.png)

**Comment by davidzhao** [comment]
@zhuwei looks like the client cannot connect due to port/IP configurations. note that client is sending 58.49.36.76 (a public IP), but the server is reporting a private IP. Ensure your server has [external IP turned on](https://github.com/livekit/livekit-server/blob/master/config-sample.yaml#L30) and their ports are mapped.

**Comment by zhuwei** [comment]
@davidzhao But I'm sure it's public IP(58.49.36.76 ), and use_external_ip is true.

**Comment by davidzhao** [comment]
<img width="700" alt="Screen Shot 2021-07-27 at 9 14 53 PM" src="https://user-images.githubusercontent.com/320582/127262744-b56967d5-0c46-4fb8-bd3c-9959b110e6ec.png">

hmm, the server is reporting a 172.20 prefix. Are you running via Docker? Can you share the server config and/or cli with me?

**Comment by zhuwei** [comment]
@davidzhao My browser is on the LAN, 172.20 appears to be a local network segment.
Are you running via Docker? No.
I run the following command:
`LIVEKIT_KEYS="APIrtQd6FrB2BU7: DvGhY69AkySKievnGuQmoashxDBxa6PaC2myNKrZE5L" ./bin/livekit-server --dev`

I didn't change the contents of config-sample.yaml file.


You can connect to this server(this is my test server):
`connect('wss://www.eeab.com.cn/wss', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjk5NDQ0OTAsImlzcyI6IkFQSXJ0UWQ2RnJCMkJVNyIsImp0aSI6ImFhYWExMTExIiwibmJmIjoxNjI3MzUyNDkwLCJ2aWRlbyI6eyJyb29tIjoibXlyb29tIiwicm9vbUpvaW4iOnRydWV9fQ.rhnAF-Sq_JhRu-ZSlLda-D5VvS_xLODC2kjRjxU0x2Q'`

**Comment by zhuwei** [comment]
I don't think the local IP 172.20.126.124 of the server should be public IP

**Comment by davidzhao** [comment]
Looks like you are running the server with no configuration. This means the server will not automatically discover your external IP. Please refer to [deployment docs](https://docs.livekit.io/guides/deploy#configuration) on the config parameter.

**Comment by zhuwei** [comment]
@davidzhao this is my config-sample.yaml, and run commad: `./bin/livekit-server --config config-sample.yaml`
```
# main TCP port for RoomService and RTC endpoint
# for production setups, this port should be placed behind a load balancer with TLS
port: 7880

# log level, valid values: debug, info, warning, error
log_level: info

# when redis is set, LiveKit will automatically operate in a fully distributed fashion
# clients could connect to any node and be routed to the same room
redis:
#  address: redis.host:6379
#  db: 0
#  username: myuser
#  password: mypassword

# WebRTC configuration
rtc:
  # UDP ports to use for client traffic.
  # this port range should be open for inbound traffic on the firewall
  port_range_start: 50000
  port_range_end: 60000
  # when set, LiveKit enable WebRTC ICE over TCP when UDP isn't available
  # this port *cannot* be behind load balancer or TLS, and must be exposed on the node
  # WebRTC transports are encrypted and do not require additional encryption
  # only 80/443 on public IP are allowed if less than 1024
  tcp_port: 7881
  # when set to true, attempts to discover the host's public IP via STUN
  # this is useful for cloud environments such as AWS & Google where hosts have an internal IP
  # that maps to an external one
  use_external_ip: true
  # when set, LiveKit will attempt to use a UDP mux so all UDP traffic goes through
  # a single port. This simplifies deployment, but mux will become an overhead for
  # highly trafficked deployments.
  # port_range_start & end must not be set for this config to take effect
  # udp_port: 7882
  # optional settings
#  # when using REMB, the max bitrate that the SFU would accept, defaults to 3Mbps
#  max_bitrate: 3145728
#  # number of packets to buffer in the SFU, defaults to 500
#  packet_buffer_size: 500
#  # optional STUN servers for LiveKit clients to use. Clients will be configured to use these STUN servers automatically.
#  # by default LiveKit clients use Google's public STUN servers
#  stun_servers:
#    - server1
#  # minimum amount of time between pli/fir rtcp packets being sent to an individual
#  # producer. Increasing these times can lead to longer black screens when participants join,
#  # while reducing them can lead to higher producer bitrates.
#  pli_throttle:
#    low_quality: 500ms
#    mid_quality: 1s
#    high_quality: 1s

# when enabled, LiveKit will expose prometheus metrics on :6789/metrics
#prometheus_port: 6789

# API key / secret pairs.
# Keys are used for JWT authentication, server APIs would require a keypair in order to generate access tokens
# and make calls to the server
keys:
  APIrtQd6FrB2BU7: DvGhY69AkySKievnGuQmoashxDBxa6PaC2myNKrZE5L

# Default room config
# Each room created will inherit these settings. If rooms are created explicitly with CreateRoom, they will take
# precedence over defaults
#room:
#  # number of seconds to leave a room open when it's empty
#  empty_timeout: 300
#  # limit number of participants that can be in a room, 0 for no limit
#  max_participants: 0
#  # only accept specific codecs for clients publishing to this room
#  # this is useful to standardize codecs across clients
#  # other supported codecs are video/h264, video/vp9
#  enabled_codecs:
#    - mime: audio/opus
#    - mime: video/vp8

# customize audio level sensitivity
#audio:
#  # minimum level to be considered active, 0-127, where 0 is loudest
#  # defaults to 30
#  active_level: 30
#  # percentile to measure, a participant is considered active if it has exceeded the
#  # ActiveLevel more than MinPercentile% of the time
#  # defaults to 40
#  min_percentile: 40
#  # frequency in ms to notify changes to clients, defaults to 500
#  update_interval: 500
#  # to prevent speaker updates from too jumpy, smooth out values over N samples
#  smooth_intervals: 4

# turn server
#turn:
#  # Uses TLS. Requires cert and key pem files by either:
#  # - using turn.secretName if deploying with our helm chart, or
#  # - setting LIVEKIT_TURN_CERT and LIVEKIT_TURN_KEY env vars with file locations, or
#  # - using cert_file and key_file below
#  # defaults to false
#  enabled: false
#  # defaults to 3478 - recommended to 443 if not running HTTP3/QUIC server
#  # only 53/80/443 are allowed if less than 1024
#  udp_port: 3478
#  # defaults to 5349 - if not using a load balancer, this must be set to 443
#  tls_port: 5349
#  # needs to match tls cert domain
#  domain: turn.myhost.com
#  # optional
#  # cert_file: /path/to/cert.pem
#  # key_file: /path/to/key.pem

```
this is my vps rule
![image](https://user-images.githubusercontent.com/1817493/127418909-6c7e62ac-443e-46d4-a0ec-36b682c1da40.png)

The problem is still there

Must turn server be set?
